
slownik = {
    #       format:
    #   "slowo":"nazwa",
    #    "ważne do końca dnia":"ważne do końca dnia",
    #    "ważne do jutra":"ważne do jutra",
    #    "małe": "mal_e",
    #    "duże": "duz_e",
    #    "bardzo duże":"bardzo_duz_e",
    #    "brak alertów pogody kosmicznej":"brak_alerto_w_pogody_kosmicznej",
    #    "alerty pogody kosmicznej":"alerty_pogody_kosmicznej",
    #    "zakłucenia radiowe":"zakl_ucenia_radiowe",
    #    "burze radiacyjne":"burze_radiacyjne",
    #"informacja o skażeniu powietrza":"informacja_o_skaz_eniu_powietrza",
    #"stan ogólny":"stan_ogolny",
    #"gdynia, ulica porębskiego":"gdynia_ul_pore_bskiego",
    #"IMGW PIB":"imgw_pib",
    #"ham QSL":"hamqsl",
    #"DX info center":"vhf_dx_info_center",
    #"państwowa agencja atomistyki":"paa",
    #"silnym wietrze": "silnym_wietrze",
    #"intensywnych opadach deszczu": "intensywnych_opadach_deszczu",
    #"opadach śniegu": "opadach_sniegu",
    #"intensywnych opadach śniegu": "intensywnych_opadach_sniegu",
    #"opadach marznących": "opadach_marznacych",
    #"zawjejach lub zamieciach śnieżnych": "zawiejach_lub_zamieciach_snieznych",
    #"oblodzeniu": "oblodzeniu",
    #"przymrozkach": "przymrozkach",
    #"roztopach": "roztopach",
    #"upale": "upale",
    #"silnym mrozie": "silnym_mrozie",
    #"gęstej mgle": "gestej_mgle",
    #"mgle intensywnie osadzającej szadź": "mgle_intensywnie_osadzajacej_szadz",
    #"burzach": "burzach",
    #"burzach z gradem": "burzach_z_gradem",
    #"silnym deszczu z burzami": "silnym_deszczu_z_burzami",
    #"gwałtownym wzroście stanów wody": "gwaltownym_wzroscie_stanow_wody",
    #"wezbraniu z przekroczeniem stannów alarmowych": "wezbraniu_z_przekroczeniem_stanow_alarmowych",
    #"wezbraniu z przekroczeniem stanów ostrzegawczych": "wezbraniu_z_przekroczeniem_stanow_ostrzegawczych",
    #"suszy hydrologicznej": "suszy_hydrologicznej"
}
slownik_auto = {
    #format: | nazwa wygeneruje się automatycznie
    #"slowo",
    #"silne",
    #"ekstremalne",
    #"burze geomagnetyczne",
    #"lokalne mgły",
    #"na wszystkich pasmach",
    #"80 i 40 metrów",
    #"30 i 20 metrów",
    #"17 i 15 metrów",
    #"12 i 10 metrów",
    #"15 metrów",
    #"bardzo dobry",
    #"pył zawieszony pm1",
    #"poziom zakłuceń",
    #"SWPC",
    #"ponad dziewięć",
    #"raport meteorologiczny"
    #"odczuwalna"
    #"komunikat o"
    #"ważny do",
    #"ważny do jutra",
    #"ważny do końca dnia",
    #"zakłucenia jonosfery"
    #"milimetr",
    #"milimetry",
    #"milimetrów",
    #"godzinę",
    #"prognoza na następną",
    #"burza z intensywnymi opadami deszczu",
    #"burza z silną ulewą",
    "dwie"
}
